apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n7n4dfmr1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n7n4dfmr1-go 
  name: n7n4dfmr1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n7n4dfmr1-go 
